# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.inputaltura = QtWidgets.QLineEdit(self.centralwidget)
        self.inputaltura.setObjectName("inputaltura")
        self.gridLayout.addWidget(self.inputaltura, 3, 3, 1, 1)
        self.btnsalvar = QtWidgets.QPushButton(self.centralwidget)
        self.btnsalvar.setObjectName("btnsalvar")
        self.gridLayout.addWidget(self.btnsalvar, 1, 7, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 780, 493))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 8)
        self.inpurlargura = QtWidgets.QLineEdit(self.centralwidget)
        self.inpurlargura.setObjectName("inpurlargura")
        self.gridLayout.addWidget(self.inpurlargura, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 2, 1, 1)
        self.btnredimensionar = QtWidgets.QPushButton(self.centralwidget)
        self.btnredimensionar.setObjectName("btnredimensionar")
        self.gridLayout.addWidget(self.btnredimensionar, 3, 7, 1, 1)
        self.btnabrir = QtWidgets.QPushButton(self.centralwidget)
        self.btnabrir.setObjectName("btnabrir")
        self.gridLayout.addWidget(self.btnabrir, 5, 7, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.inputabrir = QtWidgets.QLineEdit(self.centralwidget)
        self.inputabrir.setObjectName("inputabrir")
        self.gridLayout.addWidget(self.inputabrir, 5, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnsalvar.setText(_translate("MainWindow", "Salvar"))
        self.label_3.setText(_translate("MainWindow", "Altura"))
        self.btnredimensionar.setText(_translate("MainWindow", "Redimensionar "))
        self.btnabrir.setText(_translate("MainWindow", "Abrir "))
        self.label_2.setText(_translate("MainWindow", "Largura"))
